/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
import { TodoItem } from "./components/ghost-todo-comp/ghost-todo-comp";
export namespace Components {
    interface GhostTodoComp {
        "initTodos": string;
    }
}
declare global {
    interface HTMLGhostTodoCompElement extends Components.GhostTodoComp, HTMLStencilElement {
    }
    var HTMLGhostTodoCompElement: {
        prototype: HTMLGhostTodoCompElement;
        new (): HTMLGhostTodoCompElement;
    };
    interface HTMLElementTagNameMap {
        "ghost-todo-comp": HTMLGhostTodoCompElement;
    }
}
declare namespace LocalJSX {
    interface GhostTodoComp {
        "initTodos"?: string;
        "onTodoChange"?: (event: CustomEvent<TodoItem[]>) => void;
    }
    interface IntrinsicElements {
        "ghost-todo-comp": GhostTodoComp;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "ghost-todo-comp": LocalJSX.GhostTodoComp & JSXBase.HTMLAttributes<HTMLGhostTodoCompElement>;
        }
    }
}
